# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66364bbe0f45186fada8dfe4ddccaa1cba3552e092d1eb9ccda9a23a6e110d54688ac358c064184bf62175240a7793e002f167b5faaa90ec793ebbc5040502a9

test:
  secret_key_base: c2ee2bb818a8f52b2dce3838128c89fa6a27a2f7993d39ae01ca9c52673538a06224bc380c13cbe46bbc131930e1c2278c4caf4a3906c065a77cc31fc667eb04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
